version: '3.7'
services:
    airflow:
        container_name: airflow
        image: puckel/docker-airflow
        restart: always
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow/airflow_home/dags:/usr/local/airflow/dags
            - ./airflow/airflow_tmp:/tmp/airflow
        ports:
            - "8080:8080"
        environment:
            AWS_ACCESS_KEY_ID: minioadmin
            AWS_SECRET_ACCESS_KEY: minioadmin
            MLFLOW_S3_ENDPOINT_URL: http://192.168.99.100:9000
#    minio:
#        container_name: minio
#        image: minio/minio
#        volumes:
#            - ./minio/data:/data
#        ports:
#            - "9000:9000"
#        command: server /data
    mlflow:
        container_name: mlflow
        image: mlflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5000:5000"
