version: '3.7'
services:
    webserver:
        container_name: airflow
        image: puckel/docker-airflow
        restart: always
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow_home/dags:/usr/local/airflow/dags
            - ./airflow_tmp:/tmp/airflow
        ports:
            - "8080:8080"
